spring:
  profiles:
    active: prod
  datasource:
    platform: postgres
    url: '{cipher}AQB6qnjj1Bjo0Gm29t0fZ/CCsXuHZHFVqYHLwvQDfGhRKuysckYvDcjNzgrvt0k7m142YgLsnwx/Q0TPUmOr5NiUY9Bqp37axwNAodwBXjnnmcFu4cfsE3/JHdkRNZOxEGcH8RW/xIbnTdCNZhxdTbgdQvKZ0g+hszEjpWOv2uTZm34SajgxGBoUSjANHTxXeWNl7uO88mfDdE3h13Q9iZw5yNGr78VLNtwGETCSyQM2fiuKKrnq6ARIiYE4ic3SOWrtrRCPUgXBHiU9gfyfWeQEoA3O0bNZM50facLM4VuMSvnKdzYpVEps+Fi7jG/AP8deIMiCtf0Xupbve354/Yde4s3CAzu4Quwij5Mlifihwoj5OWl0cN8hua78dUlfO/ozhOEd++PKsDbBdTqHowXDnkzOd2iAlfAcSw49Gn4HhPnzSoeoJ+9Pyd+8MkYH88I='
    username: '{cipher}AQCYq9eI60cdGbLdQwA0LIe8T541sXbB1fQNxblv0ifvrtzzrmt5zW4c19XXy6XAAj+DqBR3ZfIIF6FdJKkxezEHP6q5Rq38vGhhz8ojcywDz9BErOg8OMIDQ+KWSWqxHO3JZp0y7IU+rh4MS2L5vPyBPI9dRQ/JubIe5yw0NqZEv4v7DJa8WlquZ4x+/T7uT6oJuiBNjU/7/vIA7+csgWQ2+/WXVr8hsI+IpPfqPovjjCoTUjSUFqeZ+kIbWFxKvpkTMJ7EjPjd1dbM21qUB9SgrXPBKPjOfSExySHyDG1wFFY1eP897NFqefQUnq3vHGCo2g5OFGaiQ/wvr5cljL82cZZ6daIk0vxvtSGTQy9hT9RjxoTRGUI2JTG6X5x9fwg='
    password: '{cipher}AQApZs3N9iEEPt9anhOEJ+axLopNk652qk7OyX4uFxcxXVyiBfpkXJ+Vx4CQHIxbLLoTB/mLYJLg1XkwueHahADej/Zt8b23+SZnOmNriInMhLbO8AgLZ6VaDlAXebexmCxXuFDdDZtyppZKkF2/YfOMRCDbqKLXP7YKva/Q9nIztlsOOwBmz1Oh6j09q7DWBL5jfBvfrVvc/tCq1B3dKQoS0VHXC8Y2Rla1RDPsJvkYWnRw4Nj67UtiohCigjcMBj1qLArLLWCG8E2wdjlQaPSQS/ArZX9Dcn4Nd+2V0BKsRG0Nyj5BUvaPbhihWzt2ZoqBQCxgIqzaFe3LNRUHuLZxUiPe8GlYDRR3KmBEsBTNMYqIHv7IPYBmqY6S5bAKtb0='
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: '{cipher}AQA2oKdLUOw0QNz+0VyZ4ppcKJPEjugAgTcxYrxKlkmPanJWuvwZA0X+fqk68qDlPaFCf5mS81KnWxQn18b505SCvBG2/Utd19n2XzQj44uav+cXTQpYZVWazTz3qMOVCH0zb/yF8J8g37P6AJ6btYbw6L0+wxUC6hh3FFOUlIMcupnpqUxkBZlu3Vag28UUkwSsHRmHxVB/EuYaqesfYcaAatezMTQn/qn0mIBcrJva22ilvcKbSGuAK9yz4zQE/W0CsEc660TWHex/15tGdvkcN1QlGc5AmRTQnZtXG+otLcVpdO/Qub74h6QUWF0G6JY3iF8t0HWsiUHtfmmSgbD2k4XISmKl0A/3aVrkBQWHM/XD4RvLeGIPLK8E11UYB4C4QSc7NsEdHAw25/momlE81OV0YwN8CF4PKBYuRZks7Q=='
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
