server:
  port: 8089

spring:
  application:
    name: scd-service-server

management:
  endpoints:
    web:
      exposure:
        include:
          [
            'configprops',
            'env',
            'health',
            'info',
            'threaddump',
            'logfile',
            'prometheus',
            'heapdump',
          ]
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.server.user.name}:${eureka.server.user.password}@localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
