server:
  port: 8089

spring:
  profiles:
    active: dev
  # datasource:
  #   platform: postgres
  #   url: '{cipher}AQAulGDp353WyZCiy3m2zKd986xx07eWibBfEX1UeS+c8sACpiWP6DL88QElkxiz/M10Zcc0TOfvT+n/zz4TkxgKh7Mdzcj/lqzJSh85h3U4Cq0REM/lSKAPHjfM81w7c4DgnGWw5U06YyEjdMnMaynCxs2axeA1yjK86kNGHo1SkVNp3JxFd/wVbzNwBNKtLv7iANAiDOXulzR5wZLQ/8gx4gTuthc6lJLkCWPu8hyY5xVvCkH4zhpFHhbO6AOelGnjYz0v6wLdeXU8mya2V/b0POTQDUhVr7xttCOIaMfZx/uO7denESv6gNXqK7llvyT0J9gWBqxSEju1wsUINbnjO37pErZg9UYLdEmFuKjaZ41iWw0gTwBYOxU5tJfxlTpmRCiwXg8JE3qY1Y3sMz3eqtO/tiJbhBRvHR45l0cw3MjZN9hl9B3X+WxiG5ZoAls='
  #   username: '{cipher}AQCYq9eI60cdGbLdQwA0LIe8T541sXbB1fQNxblv0ifvrtzzrmt5zW4c19XXy6XAAj+DqBR3ZfIIF6FdJKkxezEHP6q5Rq38vGhhz8ojcywDz9BErOg8OMIDQ+KWSWqxHO3JZp0y7IU+rh4MS2L5vPyBPI9dRQ/JubIe5yw0NqZEv4v7DJa8WlquZ4x+/T7uT6oJuiBNjU/7/vIA7+csgWQ2+/WXVr8hsI+IpPfqPovjjCoTUjSUFqeZ+kIbWFxKvpkTMJ7EjPjd1dbM21qUB9SgrXPBKPjOfSExySHyDG1wFFY1eP897NFqefQUnq3vHGCo2g5OFGaiQ/wvr5cljL82cZZ6daIk0vxvtSGTQy9hT9RjxoTRGUI2JTG6X5x9fwg='
  #   password: '{cipher}AQApZs3N9iEEPt9anhOEJ+axLopNk652qk7OyX4uFxcxXVyiBfpkXJ+Vx4CQHIxbLLoTB/mLYJLg1XkwueHahADej/Zt8b23+SZnOmNriInMhLbO8AgLZ6VaDlAXebexmCxXuFDdDZtyppZKkF2/YfOMRCDbqKLXP7YKva/Q9nIztlsOOwBmz1Oh6j09q7DWBL5jfBvfrVvc/tCq1B3dKQoS0VHXC8Y2Rla1RDPsJvkYWnRw4Nj67UtiohCigjcMBj1qLArLLWCG8E2wdjlQaPSQS/ArZX9Dcn4Nd+2V0BKsRG0Nyj5BUvaPbhihWzt2ZoqBQCxgIqzaFe3LNRUHuLZxUiPe8GlYDRR3KmBEsBTNMYqIHv7IPYBmqY6S5bAKtb0='
  #   hikari:
  #     connection-timeout: 30000
  #     maximum-pool-size: 10
  application:
    name: scd-service-server
  messages:
    basename: i18n/messages

management:
  endpoints:
    web:
      exposure:
        include:
          [
            'configprops',
            'env',
            'health',
            'info',
            'threaddump',
            'logfile',
            'prometheus',
            'heapdump',
          ]
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: '{cipher}AQA2oKdLUOw0QNz+0VyZ4ppcKJPEjugAgTcxYrxKlkmPanJWuvwZA0X+fqk68qDlPaFCf5mS81KnWxQn18b505SCvBG2/Utd19n2XzQj44uav+cXTQpYZVWazTz3qMOVCH0zb/yF8J8g37P6AJ6btYbw6L0+wxUC6hh3FFOUlIMcupnpqUxkBZlu3Vag28UUkwSsHRmHxVB/EuYaqesfYcaAatezMTQn/qn0mIBcrJva22ilvcKbSGuAK9yz4zQE/W0CsEc660TWHex/15tGdvkcN1QlGc5AmRTQnZtXG+otLcVpdO/Qub74h6QUWF0G6JY3iF8t0HWsiUHtfmmSgbD2k4XISmKl0A/3aVrkBQWHM/XD4RvLeGIPLK8E11UYB4C4QSc7NsEdHAw25/momlE81OV0YwN8CF4PKBYuRZks7Q=='
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
