server:
  port: 8089

spring:
  profiles:
    active: prod
  application:
    name: scd-service-server

management:
  endpoints:
    web:
      exposure:
        include:
          [
            'configprops',
            'env',
            'health',
            'info',
            'threaddump',
            'logfile',
            'prometheus',
            'heapdump',
          ]
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: '{cipher}AQA2oKdLUOw0QNz+0VyZ4ppcKJPEjugAgTcxYrxKlkmPanJWuvwZA0X+fqk68qDlPaFCf5mS81KnWxQn18b505SCvBG2/Utd19n2XzQj44uav+cXTQpYZVWazTz3qMOVCH0zb/yF8J8g37P6AJ6btYbw6L0+wxUC6hh3FFOUlIMcupnpqUxkBZlu3Vag28UUkwSsHRmHxVB/EuYaqesfYcaAatezMTQn/qn0mIBcrJva22ilvcKbSGuAK9yz4zQE/W0CsEc660TWHex/15tGdvkcN1QlGc5AmRTQnZtXG+otLcVpdO/Qub74h6QUWF0G6JY3iF8t0HWsiUHtfmmSgbD2k4XISmKl0A/3aVrkBQWHM/XD4RvLeGIPLK8E11UYB4C4QSc7NsEdHAw25/momlE81OV0YwN8CF4PKBYuRZks7Q=='
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
